# Generated by Django 3.1 on 2020-08-20 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_oz', models.IntegerField(max_length=5)),
                ('pieces', models.IntegerField(blank=True, max_length=5, null=True)),
                ('dashes', models.IntegerField(blank=True, max_length=5, null=True)),
                ('shake', models.BooleanField(default=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'verbose_name_plural': 'quantities',
            },
        ),
    ]
