# Generated by Django 3.1 on 2020-08-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='dashes',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='ml_oz',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='shake',
        ),
        migrations.AddField(
            model_name='quantity',
            name='qtty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
